article = [
    {
        "category": "程式",
        "img": "dev_program1.png",
        "title":  "程式開發心得（上）",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "楨",
        "write_time": "2021.11.11",
        "editer": "楨",
        "edit_time": "2021.11.12",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "程式",
        "img": "dev_program1.png",
        "title":  "程式開發心得（下）",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "楨",
        "write_time": "2021.11.11",
        "editer": "楨",
        "edit_time": "2021.11.12",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "程式",
        "img": "dev_program_top.png",
        "title":  "眼動儀設置",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "欣",
        "write_time": "2021.11.12",
        "editer": "欣",
        "edit_time": "2021.11.13",
        "ispin": True,
        "ispublish": True
    },
    {
        "category": "美術",
        "img": "dev_art1.png",
        "title":  "美術製作心得（上）",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "欣",
        "write_time": "2021.11.12",
        "editer": "欣",
        "edit_time": "2021.11.13",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "美術",
        "img": "dev_art1.png",
        "title":  "美術製作心得（下）",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "楨",
        "write_time": "2021.11.13",
        "editer": "楨",
        "edit_time": "2021.11.14",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "美術",
        "img": "dev_art2.png",
        "title":  "美術設計心得（上）",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "楨",
        "write_time": "2021.11.13",
        "editer": "楨",
        "edit_time": "2021.11.14",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "美術",
        "img": "dev_art2.png",
        "title":  "美術設計心得（下）",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "楨",
        "write_time": "2021.11.11",
        "editer": "",
        "edit_time": "",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "美術",
        "img": "dev_art_top.png",
        "title":  "場景設計介紹",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "楨",
        "write_time": "2021.11.11",
        "editer": "",
        "edit_time": "",
        "ispin": True,
        "ispublish": True
    },
    {
        "category": "企劃",
        "img": "dev_level1.png",
        "title":  "關卡製作心得",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "欣",
        "write_time": "2021.11.11",
        "editer": "",
        "edit_time": "",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "企劃",
        "img": "dev_level1.png",
        "title":  "關卡製作心得2",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "欣",
        "write_time": "2021.11.11",
        "editer": "",
        "edit_time": "",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "企劃",
        "img": "dev_level1.png",
        "title":  "關卡製作心得3",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "欣",
        "write_time": "2021.11.11",
        "editer": "",
        "edit_time": "",
        "ispin": False,
        "ispublish": True
    },
    {
        "category": "企劃",
        "img": "dev_level_top.png",
        "title":  "世界觀介紹",
        "content": "從初期所有討論，主題、載體和分享製作畢專的心得，與老師討論的紀錄。",
        "writer": "欣",
        "write_time": "2021.11.11",
        "editer": "",
        "edit_time": "",
        "ispin": True,
        "ispublish": True
    }
]
